const judete = [
  'BUCUREȘTI',
  'ALBA',
  'ARAD',
  'ARGEȘ',
  'BACĂU',
  'BIHOR',
  'BISTRIȚA-NĂSĂUD',
  'BOTOȘANI',
  'BRAȘOV',
  'BRĂILA',
  'BUZĂU',
  'CARAȘ-SEVERIN',
  'CĂLĂRAȘI',
  'CLUJ',
  'CONSTANȚA',
  'COVASNA',
  'DÂMBOVIȚA',
  'DOLJ',
  'GALAȚI',
  'GIURGIU',
  'GORJ',
  'HUNEDOARA',
  'IALOMIȚA',
  'IAȘI',
  'ILFOV',
  'MARAMUREȘ',
  'MEHEDINȚI',
  'MUREȘ',
  'NEAMȚ',
  'OLT',
  'PRAHOVA',
  'SATU MARE',
  'SĂLAJ',
  'SIBIU',
  'SUCEAVA',
  'TELEORMAN',
  'TIMIȘ',
  'TULCEA',
  'VASLUI',
  'VÂLCEA',
  'VRANCEA',
];

const sectoare = ['SECTOR 1', 'SECTOR 2', 'SECTOR 3', 'SECTOR 4', 'SECTOR 5', 'SECTOR 6'];

const case_de_danatete = [
  'BUCUREȘTI - CAS_B',
  'ALBA - CASAB',
  'ARAD - CASAR',
  'ARGEȘ - CASAG',
  'BACĂU - CASBC',
  'BIHOR - CASBH',
  'BISTRIȚA-NĂSĂUD - CASBN',
  'BOTOȘANI - CASBT',
  'BRAȘOV - CASBV',
  'BRĂILA - CASBR',
  'BUZĂU - CASBZ',
  'CARAȘ-SEVERIN - CASCS',
  'CĂLĂRAȘI - CASCL',
  'CLUJ - CASCJ',
  'CONSTANȚA - CASCT',
  'COVASNA - CASCV',
  'DÂMBOVIȚA - CASDB',
  'DOLJ - CASDJ',
  'GALAȚI - CASGL',
  'GIURGIU - CASGR',
  'GORJ - CASGJ',
  'HUNEDOARA - CASHD',
  'IALOMIȚA - CASIL',
  'IAȘI - CASIS',
  'ILFOV - CASIF',
  'MARAMUREȘ - CASMM',
  'MEHEDINȚI - CASMH',
  'MUREȘ - CASMS',
  'NEAMȚ - CASNT',
	'OLT - CASOT',
	'OPSNAJ - CAS_A',
  'PRAHOVA - CASPH',
  'SATU MARE - CASSM',
  'SĂLAJ - CASSJ',
  'SIBIU - CASSB',
  'SUCEAVA - CASSV',
  'TELEORMAN - CASTR',
	'TIMIȘ - CASTM',
	'TRANSPORTURI - CAS_T',
  'TULCEA - CASTL',
  'VASLUI - CASVS',
  'VÂLCEA - CASVL',
  'VRANCEA - CASVN',
];

export { judete, sectoare, case_de_danatete };
